### ISSUE TITLE
Design Product Logo

### ISSUE THREAD

**Issue by RonnieLutalo** [OSCA-Kampala-Chapter/Windows-Musawo#19]
**Design Brief**

**About Product:** A free solution that automatically runs in the background of your Windows Operating System Device to routinely clean up Junk files, save storage/space and improve performance, without you having to do it manually every time. Junk files are temporary files that were created so that your computer/device could perform a task, such as opening a document, viewing an image, or browsing the internet. These files are useful at the moment, but once they’ve served their purpose, they’re just junk, system junk files that clog up a device and cause poor performance.

**Inspiration:**

- The Logo should be able to come across as Tech savvy, Futuristic, and Simple but still communicate the purpose of the product.
- It should be something that can easily be used as an icon. Ideas and suggestions by the Designer are highly welcome. Feel free to start a conversation in the comments section.  
- Feel free to suggest theme colors not more than 3, the primary theme color should be one of those three.

**Suggested Design Tool**:
- Adobe illustrator or any other tool that can enable the designer produce vector graphics. 

**Expected Output**:
- png file format for the Product Logo on a transparent background

**Use Cases for the Logo Design**:
- We intend to use [Microsoft Store](https://apps.microsoft.com/store/apps) as our Distribution channel for the product (Windows Musawo). We are going to use this Logo there mostly and in our social media marketing campaigns. Be sure to look at the [Microsoft Store](https://apps.microsoft.com/store/apps) and how apps display their logo to get an idea of how our Logo could fit in as well. For more clarity questions, start a discussion in the comments

**Comment by Victorayo** [comment]
Hi Ronnie, can I be assigned this?

**Comment by RonnieLutalo** [comment]
Thank you @Victorayo! We're assigning you the issue. Don't hesitate to ask whenever you have questions about anything to help you deal with the issue.

**Comment by Victorayo** [comment]
> @Victorayo! Go ahead please. Don't hesitate to ask any clarifying questions you may have. Thanks!

Hi Ronnie, the name of the Windows am designer logo for is "Musawo" right?

**Comment by RonnieLutalo** [comment]
@Victorayo The name of the product is **Windows Musawo**. And the Logo is being designed for it. I hope this is clear now.

**Comment by Victorayo** [comment]
> @Victorayo The name of the product is **Windows Musawo**. And the Logo is being designed for it. I hope this is clear now. 😊

Yeah it is.

**Comment by Victorayo** [comment]
I sent 

> @Victorayo The name of the product is **Windows Musawo**. And the Logo is being designed for it. I hope this is clear now. blush

Hi Ronnie, I sent some pull request. Kindly check them

**Comment by RonnieLutalo** [comment]
Thank you so much, great stuff.
