### ISSUE TITLE
Design project GitHub cover image for social preview online

### ISSUE THREAD

**Issue by RonnieLutalo** [OSCA-Kampala-Chapter/Windows-Musawo#8]
Design graphics for the project's repository. The first including the GitHub image for social preview online. Required dimensions (1280×640px for best display) pixels. You may suggest more ideas on this in comments. This task however highly depends on completion of #19

**Comment by Victorayo** [comment]
Hi Ronnie,
Can I be assigned this?

**Comment by RonnieLutalo** [comment]
Hi @Victorayo! Sure! Go ahead please. Thanks!
